# Generated by Django 4.0.4 on 2023-09-05 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completiondate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
