# Generated by Django 4.0.4 on 2023-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_completiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remainingdays',
            field=models.DateField(blank=True, null=True),
        ),
    ]
