# Generated by Django 4.0.4 on 2023-09-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_remainingdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='remainingdays',
        ),
    ]
